export const restArray = [
  {
    id: 0,
    title: 'Пицца плюс',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest-1.jpg',
  },
  {
    id: 1,
    title: 'Тануки',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest-2.jpg',
  },
  {
    id: 2,
    title: 'FoodBand',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest-3.jpg',
  },
  {
    id: 3,
    title: 'Жадина-пицца',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest-4.jpg',
  },
  {
    id: 4,
    title: 'Точка еды',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest-5.jpg',
  },
  {
    id: 5,
    title: 'PizzaBurger',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest-6.jpg',
  },
];